; general structure
blocks = [ block ] *( strong-delimiter, block )
delimiter = weak-delimiter / strong-delimiter
weak-delimiter = [ CR ] LF
strong-delimiter = 2weak-delimiter *( weak-delimiter )

; blocks
block = title / paragraph / quote / callout / code-block / math-block / image / footnotes / tag
title = 1*6# SP content
paragraph = content *( weak-delimiter content )
quote = ">" content *( weak-delimiter ">" content ) [ weak-delimiter paragraph ]
callout = ":::" *%x61-7A *( delimiter, content ) weak-delimiter ":::"
code-block = "```" *ALPHA *( delimiter content ) weak-delimiter "```" [ weak-delimiter paragraph ]
math-block = "$$$" *( delimiter content ) weak-delimiter "$$$" [ weak-delimiter paragraph ]
image = "!" link [ weak-delimiter paragraph ]
list-unordored = "- " paragraph *( weak-delimiter, "- ", paragraph )
list-ordored = ". " paragraph *( weak-delimiter ". " paragraph )
footnotes = "<" content ">:" paragraph *( weak-delimiter, "<", content, ">:", paragraph )
tag = "#" content

; content of a block
content = *( ASCII - weak-delimiter / bold / italic / code-inline / math-inline / link / ref )
bold = "*" content "*"
italic = "_" content "_"
code-inline = "`" content "`"
math-inline = "$" content "$"
link = "[" [ content ] "](" content ")"
ref = "<" content ">"
